name: Generate Snake

on:
  schedule: 
    - cron: "0 0 * * *"  # Runs at every 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: KaranKumar2326
          outputs: svg
          
      - name: Push the generated snake
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          file: github-contribution-grid-snake.svg
